version: '3.9'
services:
  app:
    restart: always
    image: ghcr.io/it-s-bread/online-shop-front:latest
    build:
      dockerfile: Dockerfile
      context: .
      target: base
#    ports:
#      - 80:3000
    env_file:
      - .env
    command: ["npm", "run", "start"]

  nginx:
    restart: "${DOCKER_RESTART_POLICY:-always}"
    env_file:
      - .env
    image: nginx:local
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
      args:
          DOMAIN: "${DOMAIN:-hleb365.ru}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.virtual_host.conf:/etc/nginx/conf.d/virtual_host.conf:ro
      - certbot-www:/var/www/certbot/:ro
      - data-certs:/etc/nginx/ssl/:rw

  certbot:
    restart: "no"
    image: certbot/certbot:latest
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - data-certs:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal -d hleb365.ru --agree-tos --email pr0sto@hotmail.com
    depends_on:
      - nginx

volumes:
  data-certs:
    driver: local
  certbot-www:
    driver: local
