export const API_URL = 'http://23.111.124.118:3005';
export const API_CATEGORY = '/category';
export const API_PRODUCT = '/item';
export const API_PRODUCT_ID = (id:string) => `/item/${id}`;
export const API_CATEGORY_ITEMS = (id:string) => `/item/category/${id}`;
export const API_ORDER_AMOUNT = '/order/amount';
export const API_ORDER = '/order';
export const API_ORDER_ID = (id:string) => `/order/${id}`;
export const API_ORDER_PLATI = (id:string) => `/order/plati/${id}`;
export const API_ORDER_COMPLETE_ID = (id:string) => `/order/complete/${id}`;
