import React from "react";
import { Inter } from 'next/font/google'
import Providers from "@/app/providers";
import type {Metadata} from "next";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface IRootLayout {
  children: React.ReactNode,
}

const RootLayout = ({children}:IRootLayout) => {
  return (
      <html lang="ru">
          <body className={inter.className}>
              <Providers>
                  {children}
              </Providers>
          </body>
      </html>
  )
}

export default RootLayout;
