name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - spr0sto
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  repository-projects: read

jobs:

#  hadoLint:
#    name: 'hadoLint'
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@v2
#
#      - name: 'Running'
#        uses: hadolint/hadolint-action@master
#        with:
#          dockerfile: "Dockerfile"
#          recursive: true
#          config: ./.hadolint.yaml

#  YAMLLint:
#    name: 'YAMLLint'
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@v2.3.4
#
#      - name: 'Installing'
#        run: python -m pip install yamllint
#
#      - name: 'Running'
#        run: yamllint -c .yamllint.yml .

#  Build:
#    name: 'Build'
#    needs: [YAMLLint, hadoLint]
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#    #if: github.ref_name == github.event.repository.default_branch
#    env:
#      REGISTRY: ghcr.io
#      TAG_NAME: latest
#      CACHE_IMAGE_NAME: buildcache
#    steps:
#
#      - uses: actions/checkout@v3
#
#      - name: 'Exporting lowercase image names'
#        shell: bash
#        run: |
#          : "${{ env.REGISTRY }}/${{ github.repository }}:latest"
#          echo "IMAGE_TAG=${_,,}" | tee -a "$GITHUB_ENV"
#
#      - name: 'Login to GHCR'
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: 'Set up docker Buildx'
#        id: buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: 'Building and push docker image'
#        uses: docker/build-push-action@v3
#        with:
#          builder: ${{ steps.buildx.outputs.name }}
#          context: ./
#          file: ./Dockerfile
#          target: base
#          tags: "${{ env.IMAGE_TAG }}"
#          push: true

  deploy:
#    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/it-s-bread/infrastructure:latest
      credentials:
         username: ${{ github.actor }}
         #password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
         password: ${{ secrets.GITHUB_TOKEN }}
#    if: github.ref_name == github.event.repository.default_branch
    env:
      SSH_RSA_KEY: ${{ secrets.SSH_KEY_ROOT }}
    steps:

      - uses: actions/checkout@v2

      - name: 'Prerequisites'
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && echo "$SSH_RSA_KEY" > ~/.ssh/id_rsa

      - name: 'Deploing'
        shell: bash
        run: |
          printenv && pwd && ls -la && cat ~/.ssh/id_rsa && cat site.yml
          ansible-playbook site.yml --check --diff -v
